---
title: "Advandced Data Science Project RMD"
author: "Nikita Stempniewicz"
date: "September 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Analysis Assignment 

Perform an analysis of "data scientist" jobs listed on job boards and on the employment pages of major companies. What are the most common skills that employers look for? What are the most unique skills that employers look for? Where are the types of companies that employ the most data scientists?

### Data source

All the data for this analysis was scraoed from Glassdoor.com. 

  * First, I get data, i.e., job  id, employer id, job title, salaries (if available), locations, employer from the search results for data scientist.
  * Next, using the job id from the search results in the previous step, I build the URL for the individual job posts on glassdoor and get the raw job descriptions which includes text information on qualifications which I will later query to build structured fields.
  *Finally, using the employer id from the search results, I build the URL for the employer page on glassdoor, and get the raw text from the employer description field, which includes things like, size, industry, year founded.

Other potential data sources to consider if I have time

  * Job Boards
    + Indeed
    + Monster
    + LinkedIn
  * Major Companies websites? 
    + Amazon 
    + Google
    + Facebook
    + IBM
    + Optum
    + United
    + Tableau
    
### Potential Analyses
Data will be extracted from websites using web scrapping methods (e.g., rvest). We will extract data for the following information when possible.

  * Most common skills
	* Unique Skills??
  * Cities/locations
  * Companies 
    + Size
    + Industry
    + Perks
  * Days posted (length of time)
  * Years work experience
  * Educational requirements
  * Position title
  * Salary
	
**Potential Secondary Analysis**	

find a control job title to search and compare results, e.g., an alternate job that data scientist would become had they not chosen to be data scientists? (statisticians?, software developer?)

